name: Playwright Screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Generate screenshot
        id: "screenshot"
        uses: natainditama/screen-snap@main
        with:
          url: "https://natainditama.pages.dev/"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "docs: Update ${{ steps.screenshot.outputs.filename }}"
          add: "${{ steps.screenshot.outputs.filename }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
