name: Test Screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run screen-snap
        uses: natainditama/glance/@main
        with:
          url: https://github.com

  screenshots-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master # Required for headful puppeteer
        env:
          CI: "true"

      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://github.com

      - uses: actions/upload-artifact@v4 # Uplaod screenshots to Actions Artifacts via actions/upload-artifact@v2
        with:
          path: screenshots
          name: Download-screenshots
